apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    matchLabels:
      service: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
        - image: mostafamgomaa/udagram-api-user:v3
          name: backend-user
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
